#!/usr/bin/env python3
"""apply_renames.py -- apply tools/renames.json to the generated sources.

Renames FUN_/s_/DAT_ identifiers (word-boundary, longest first) in
linux/bblit_game.c, linux/bblit_game.h, linux/port_main.c and linux/shim/*.c.
linux/data_syms.[ch] are regenerated by gen_headers.py (which reads the same
map) and are not edited here.

Aborts before touching anything if a new name already exists in the tree, so a
partial application can never happen.
"""
import json, re, sys, glob

REN = 'tools/renames.json'
FILES = (['linux/bblit_game.c', 'linux/bblit_game.h', 'linux/port_main.c'] +
         sorted(glob.glob('linux/shim/*.c')))

def main():
    ren = json.load(open(REN))
    sym_map = {}
    for k, v in ren.items():
        if re.fullmatch(r'[0-9a-fA-F]{8}', k):
            sym_map['FUN_' + k] = v
        elif k.startswith(('DAT_', '_DAT_', 'PTR_')):
            sym_map[k] = v
        else:
            sys.exit(f'renames.json: unrecognized key {k!r}')
    for line in open('tools/symbols.csv'):
        p = line.rstrip('\n').split('|')
        if p[0] == 'DATA' and p[4].startswith('s_') and p[1] in ren:
            sym_map[re.sub(r'[^A-Za-z0-9_]', '_', p[4])] = ren[p[1]]

    texts = {f: open(f).read() for f in FILES}
    allsrc = '\n'.join(texts.values())
    for old, new in sym_map.items():
        if re.search(r'\b' + re.escape(new) + r'\b', allsrc):
            sys.exit(f'collision: {new} already present (would rename {old})')

    pairs = sorted(sym_map.items(), key=lambda kv: -len(kv[0]))
    total = 0
    for f, t in texts.items():
        n = 0
        for old, new in pairs:
            if old in t:
                n += len(re.findall(r'\b' + re.escape(old) + r'\b', t))
                t = re.sub(r'\b' + re.escape(old) + r'\b', new, t)
        if n:
            open(f, 'w').write(t)
        print(f'{f}: {n}')
        total += n
    print(f'total {total} renames')

if __name__ == '__main__':
    main()
